# Introduction To NumPy Arrays
Scenario:
Imagine you are working with a small weather-monitoring team.
The team recorded the temperature in °C for three days:
temperatures = [27.5, 29.0, 28.5]
Your job is to convert this information into a NumPy array and inspect what you have.


TASK 1: Import NumPy

In [2]:
import numpy as np

''this code ran without an error which means Numpy is available in
our notebook environment''

TASK 2: Create Array

In [3]:
#converting list into an array
temperatures = [27.5, 29.0, 28.5]
temperature_array = np.array(temperatures)

print(temperature_array)

[27.5 29.  28.5]


TASK 3: Inspect The Data Type

In [4]:
# using NumPy attributes to get the data type of the array
temperature_array.dtype

dtype('float64')

TASK 4: Create a 2D Array

In [6]:
# creating variable
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]
# to convert the list to numpy 2d array
weather_data_array = np.array(weather_data)

print(weather_data_array)

[[27.5 28.  29.5]
 [28.  29.  30. ]]


# Python Lists vs NumPy Arrays
Scenario:
You are working with a small retail business.
The business recorded the number of products sold by two sales representatives over three days.
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]
The manager wants to know the combined sales for each day.
The expected result is:
[15, 25, 35]


TASK 1: Try With Python Lists

In [8]:
#creating variables
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

print(sales_timothy + sales_brenda)

[10, 15, 20, 5, 10, 15]


In [ ]:
''Python concatenated the two lists instead of actually adding them
up to get our expected result.
This happened because Python recognizes the '+' operator under
Lists to be for concatenation and not for element_wise maths. 

TASK 2: Convert To Numpy Arrays

In [9]:
sales_timothy_array = np.array(sales_timothy)
sales_brenda_array = np.array(sales_brenda)

print(sales_timothy_array + sales_brenda_array)

[15 25 35]


TASK 3: Compare Both Results

In [ ]:
#   Approach       ||     Result
#                  ||
#  Python Lists    ||    [10, 15, 20, 5, 10, 15]
#                  ||
#  NumPy arrays    ||    [15, 25, 35]
#
#
#NumPy is useful here because it allows us to express element_wise 
#mathematical operations directly and faster without having to
#manually write a loop for basic numerical operations.'''

CHALLENGE


Create two new arrays:
online_sales
store_sales
Use five days of imaginary sales data.
For example, you might have:
Monday
Tuesday
Wednesday
Thursday
Friday
Calculate the combined sales for each day.
Then create a second operation that calculates the difference between online and store sales.


In [14]:
# creating lists
online_sales = [2000, 1000, 1500, 2500, 4000] #sales for mon-fri
store_sales = [5000, 10000, 7000, 7500, 20000] #sales for mon-fri

#creating array
online_sales_array = np.array(online_sales)
store_sales_array = np.array(store_sales)

#to calculate the combined sales for each day
combined_sales = online_sales_array + store_sales_array

#to calculate the difference between online and store sales
difference = (store_sales_array - online_sales_array)

print("Combined Sales:", combined_sales)
print("Difference:", difference)

Combined Sales: [ 7000 11000  8500 10000 24000]
Difference: [ 3000  9000  5500  5000 16000]


# MINI PROJECT
# WEATHER TEMPERATURE ANALYSIS WITH NUMPY

PROJECT SCENARIO

Imagine you have been given a small dataset from a weather-monitoring station.
The station recorded daily temperatures for one week.
Your job is to use NumPy to turn the raw numerical data into something that can be analyzed.
Here is your dataset:
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
You have been asked to perform some basic numerical analysis.



PART 1: CREATE THE DATASET

In [4]:
#to get numpy running
import numpy as np

# to create a python list
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

# to convert the list to NumPy array
temperature_array = np.array(temperatures)

#to display result
print(temperature_array)

[27.5 29.  30.5 28.  31.  32.5 30. ]


PART 2: UNDERSTAND THE ARRAY

In [6]:
#Question 1
#Is the temperature array 1D or 2D?
#Answer : A 1D array
#
#Question 2
#Would you describe it as a vector or matrix?
#Answer : A Vector

#Question 3
#What is its data type?
#Answer : A float64
print(temperature_array.dtype)

#Question 4
#How many temperature observations are present?
#Answer : 7 observations
print(len(temperature_array))

float64
7


PART 3: PERFORM NUMERICAL OPERATIONS

The weather team wants to compare temperatures.
Create another NumPy array representing the target temperature for each day:
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
Convert it to a NumPy array.

Now calculate:

— Temperature Difference

— Temperature Increase by 2°C


In [9]:
#creating a Numpy array
target = np.array([28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0])

#TASK A - To calculate the temperature difference
temp_difference = temperature_array - target

#TASK B - To calaculate the temperature increase by 2°C
temp_increase = temperature_array + 2

#to display result
print("Temperature Difference:", temp_difference)
print("Temperature Increase 2°C:", temp_increase)

Temperature Difference: [-0.5  1.   1.5  0.   1.   2.5  1. ]
Temperature Increase 2°C: [29.5 31.  32.5 30.  33.  34.5 32. ]


PART 4: THINK LIKE AN ANALYST

Business Question 1
Which day appears to have the highest recorded temperature?
Answer:- Day 6(Saturday) with a temperature of 32°C.


Business Question 2
On which days was the recorded temperature above the target?
Answer:- Day2(Tuesday), Day3(Wednesday), Day5(Friday), Day6(Saturday), and Day7(Sunday).


Business Question 3
What does the temperature difference tell the weather-monitoring team?
Answer:- It helps the team to identify days when temperature deviated from their expected targets.


Business Question 4
Why would using a NumPy array be more convenient than keeping the temperatures only as a Python list for these numerical operations?
Answer:- NumPy makes calculations easier and faster especially when dealing with a bulky dataset. NumPy allows operations to be performed element by element across the entire array without manually processing each value with a loop.


# MINI PROJECT CHALLENGE

Imagine the weather station has three locations:
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]


Your task is to create NumPy arrays for all three locations.
Then answer:
Challenge 1
Which location recorded the highest temperature on each day?


Challenge 2
Create a calculation that increases every recorded temperature by 1°C.


Challenge 3
Create a calculation that compares Lagos temperatures with Abuja temperatures.


Challenge 4
Explain why NumPy becomes increasingly useful as the amount of numerical data grows.


In [15]:
# creating an array
lagos = np.array([27.5, 29.0, 30.5, 28.0, 31.0])
abuja =np.array([25.0, 28.0, 29.5, 30.0, 32.0])
ibadan = np.array([26.5, 28.5, 29.0, 27.5, 30.5])

#=====================================================
#CHALLENGE 1: To get the location with highest record
#=====================================================

locations = np.array([lagos, abuja, ibadan]) #combines it to a 2D array

# to find the position of the highest temp for each day
highest_location = np.argmax(locations,axis = 0)

#to create names for the locations
location_names = np.array(["Lagos", "Abuja", "Ibadan"])

#to loop through
for day, index in enumerate (highest_location, start = 1):
    print("Day", day, ":", location_names[index])
          

Day 1 : Lagos
Day 2 : Lagos
Day 3 : Lagos
Day 4 : Abuja
Day 5 : Abuja


In [17]:
#=======================================================
#CHALLENGE 2: To increase every recorded temperature by 1°C
#========================================================

lagos_increase = lagos + 1
abuja_increase = abuja + 1
ibadan_increase = ibadan + 1

print(f"""
Lagos : {lagos_increase}
Abuja : {abuja_increase}
Ibadan : {ibadan_increase}""")


Lagos : [28.5 30.  31.5 29.  32. ]
Abuja : [26.  29.  30.5 31.  33. ]
Ibadan : [27.5 29.5 30.  28.5 31.5]


In [18]:
#=======================================================
#CHALLENGE 3: To compare Lagos temperature with Abuja's
#=======================================================

#subtracting Abuja temp from Lagos temp
#Negative values shows Abuja was warmer
#Positive value shows Lagos was warmer

temperature_difference = lagos - abuja

# to display result
print("Lagos vs Abuja :", temperature_difference)


Lagos vs Abuja : [ 2.5  1.   1.  -2.  -1. ]


In [ ]:
#=========================
#CHALLENGE 4:
#=========================
'''NumPy becomes increasingly useful as the amount of numerical data
grows because as data grows, writing manual loops becomes slow and 
prone to error. NumPy allows many values to be stored and processed
efficiently as arrays. Numerical operations can be performed across
the entire dataset without manually calculating each value.'''

# MINI PROJECT REPORT

In [21]:
print(f"""
========================================
WEATHER TEMPERATURE ANALYSIS WITH NUMPY
========================================


PROJECT INTRODUCTION
This project uses NumPy to analyze temperature data collected from 
weather-monitoring stations. The analysis involves creating NumPy 
arrays, inspecting their properties, performing numerical 
calculations, comparing recorded temperatures with target 
temperatures, and comparing temperatures across different locations.

DATASET
The dataset contains temperature readings recorded over seven days.

ARRAY INSPECTION
The temperature data is a 1D array containing 7 observations. 
Its data type is float64.

NUMERICAL OPERATIONS
The temperature differences were calculated by subtracting the 
target temperatures from the recorded temperatures. 
The temperatures were also increased by 2°C using NumPy.

LAGOS vs ABUJA COMPARISON
Lagos and Abuja temperature arrays were compared by subtracting 
Abuja temperatures from Lagos temperatures.

FINDINGS
1. The highest recorded temperature during the week was 32.5°C on
    Day 6.
2. The recorded temperature was above the target temperature on 
    Days 2, 3, 5, 6 and 7.
3. Lagos recorded higher temperatures than Abuja during the first
   three days, while Abuja recorded higher temperatures during 
   Days 4 and 5.

CONCLUSION
This project demonstrated how NumPy can be used to convert Python 
lists into numerical arrays and perform numerical analysis. 
The analysis showed how to inspect array dimensions and data types,
calculate temperature differences, increase temperatures, and 
compare temperature data between locations.
""")


WEATHER TEMPERATURE ANALYSIS WITH NUMPY


PROJECT INTRODUCTION
This project uses NumPy to analyze temperature data collected from 
weather-monitoring stations. The analysis involves creating NumPy 
arrays, inspecting their properties, performing numerical 
calculations, comparing recorded temperatures with target 
temperatures, and comparing temperatures across different locations.

DATASET
The dataset contains temperature readings recorded over seven days.

ARRAY INSPECTION
The temperature data is a 1D array containing 7 observations. 
Its data type is float64.

NUMERICAL OPERATIONS
The temperature differences were calculated by subtracting the 
target temperatures from the recorded temperatures. 
The temperatures were also increased by 2°C using NumPy.

LAGOS vs ABUJA COMPARISON
Lagos and Abuja temperature arrays were compared by subtracting 
Abuja temperatures from Lagos temperatures.

FINDINGS
1. The highest recorded temperature during the week was 32.5°C on
    Day 6.
2. The reco

# BONUS CHALLENGE

In [25]:
import numpy as np
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

#Predictions
# x+y = (3, 7, 11)
# x-y = (1, 1, 1)
# x*y = (2, 12, 30)

# To get python's output
print(x + y)
print(x - y)
print(x * y)

'''What I Learned :
Arithmethical operations were performed across an entire array
without manually processing each value'''

[ 3  7 11]
[1 1 1]
[ 2 12 30]


'What I Learned :\nArithmethical operations were performed across an entire array\nwithout manually processing each value'